<a href="https://colab.research.google.com/github/Franciscopd15/Bibliotecas_Python_FJPD/blob/main/Desafio_Curso_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desaf√≠o del Curso 1 de Pandas

In [23]:
import pandas as pd

url = 'https://gist.githubusercontent.com/ahcamachod/807a2c1cf6c19108b2b701ea1791ab45/raw/fb84f8b2d8917a89de26679eccdbc8f9c1d2e933/alumnos.csv'

alumnos = pd.read_csv(url)

In [24]:
alumnos.head()

    Nombre  Edad  Nota Aprobado
0  Alberto    20   7.5     True
1      Ana    18   NaN    False
2   Camila    27   2.5    False
3    David    18   5.0    False
4    Brian    21  10.0     True

In [25]:
alumnos.shape

(18, 4)

In [26]:
alumnos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    18 non-null     object
 1   Edad      18 non-null     int64
 2   Nota      12 non-null     float64
 3   Aprobado  18 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 708.0+ bytes

In [27]:
'''El m√©todo describe obtiene datos estadisticos de las columnas que contienen
n√∫meros en un DataFrame y los genera solo de esos valores'''
alumnos.describe()

            Edad       Nota
count  18.000000  12.000000
mean   25.500000   6.841667
std     6.070662   2.264532
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000

In [28]:
alumnos.isnull().sum()

Nombre      0
Edad        0
Nota        6
Aprobado    0
dtype: int64

In [29]:
alumnos.interpolate(inplace=True)

<ipython-input-29-4afb0acbe290>:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  alumnos.interpolate(inplace=True)

In [30]:
alumnos.isnull().sum()

Nombre      0
Edad        0
Nota        0
Aprobado    0
dtype: int64

In [31]:
df_remove = alumnos.query('Nombre == "Alicia" | Nombre == "Carlos"' ).index

In [32]:
alumnos.drop(df_remove, axis=0, inplace=True)

In [33]:
seleccion = alumnos['Aprobado'] == True
alumnos[seleccion]

Empty DataFrame
Columns: [Nombre, Edad, Nota, Aprobado]
Index: []

In [34]:
alumnos.to_csv('alumnos.csv', index=False)

In [35]:
alumnos['Puntos_extras'] = alumnos['Nota']*0.4

In [36]:
alumnos

      Nombre  Edad       Nota   Aprobado  Puntos_extras
0    Alberto    20   7.500000       True       3.000000
1        Ana    18   5.000000      False       2.000000
2     Camila    27   2.500000      False       1.000000
3      David    18   5.000000      False       2.000000
4      Brian    21  10.000000       True       4.000000
5      Bruna    23   8.500000      False       3.400000
6    Daniela    21   7.000000       True       2.800000
9     Victor    28   5.233333      False       2.093333
10    Danilo    21   4.866667      False       1.946667
11   Ignacio    24   4.500000      False       1.800000
12  Stephany    26  10.000000       True       4.000000
13    Miriam    25   9.000000       True       3.600000
14     Pablo    37   8.000000      False       3.200000
15    Milena    29   7.000000       True       2.800000
16     Lucas    33   7.500000      False       3.000000
17     Nadia    34   8.000000  Verdadero       3.200000

In [37]:
alumnos['Notas_finales'] = alumnos['Nota'] + alumnos['Puntos_extras']

In [43]:
alumnos['Aprobado_final'] = alumnos['Notas_finales'].apply(lambda x: 'True' if x >= 7 else 'False')
alumnos

,Nombre,Edad,Nota,Aprobado,Puntos_extras,Notas_finales,Aprobado_final
0,Alberto,20,7.500000,True,3.000000,10.500000,True
1,Ana,18,5.000000,False,2.000000,7.000000,True
2,Camila,27,2.500000,False,1.000000,3.500000,False
3,David,18,5.000000,False,2.000000,7.000000,True
4,Brian,21,10.000000,True,4.000000,14.000000,True
5,Bruna,23,8.500000,False,3.400000,11.900000,True
6,Daniela,21,7.000000,True,2.800000,9.800000,True
9,Victor,28,5.233333,False,2.093333,7.326667,True
10,Danilo,21,4.866667,False,1.946667,6.813333,False
11,Ignacio,24,4.500000,False,1.800000,6.300000,False
12,Stephany,26,10.000000,True,4.000000,14.000000,True
13,Miriam,25,9.000000,True,3.600000,12.600000,True
14,Pablo,37,8.000000,False,3.200000,11.200000,True
15,Milena,29,7.000000,True,2.800000,9.800000,True
16,Lucas,33,7.500000,False,3.000000,10.500000,True
17,Nadia,34,8.000000,Verdadero,3.200000,11.200000,True

In [45]:
seleccion = (alumnos['Aprobado'] == False) & (alumnos['Aprobado_final'] == True)
alumnos[seleccion]

Empty DataFrame
Columns: [Nombre, Edad, Nota, Aprobado, Puntos_extras, Notas_finales, Aprobado_final]
Index: []